#配置信息文件application.yaml只能有一个起作用，所以，在定义多个时，要进行声明，或者说仅定义一个
##声明端口
#server:
#  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.179.128:3306/lease
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
     redis:
       host: 192.168.179.128
       port: 6379
       database: 0

  #这里引入了minion的配置文件
  profiles:
     active: minio

      #--------------------------------------------------
  #用于打印框架生成的sql语句，便于调试的日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

      #用于配置全局逻辑删除，默认值为0，删除为1，字段名为isDeleted
  global-config:
      db-config:
        logic-delete-value: 1
        logic-delete-field: isDeleted
        logic-not-delete-value: 0

springdoc:
  default-flat-param-object: true

