spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///hello_mp?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8