spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///hello_mp
#上面为SpringBoot提供了数据库连接对象的属性



mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  #上面为项目中所有的类，都指定了逻辑删除的字段为deleted（因为所有的表都要拥有逻辑删除属性，
  #所以此设定可以让我们不用每个逻辑删除属性都设置@TableLogic，只要保证所有逻辑删除的字段名称为deleted且类型为Integer类型即可）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  logging:
  level:
    com.atguigu.mapper: debug
  #上面的作用是，为日志功能设置为debug模式。此时我们能看见SQL的执行语句




